<?php

use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\LanguageController;
use App\Http\Controllers\Auth\LoginController;
use Illuminate\Support\Facades\Route;

Route::redirect('/', '/admin');

Route::prefix('admin')->name('admin.')->group(function () {

    // Guest routes (login)
    Route::middleware('guest.admin')->group(function () {
        Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
        Route::post('login', [LoginController::class, 'login'])->name('login.attempt');
    });

    // Language switch (available to both guests and authed users)
    Route::post('lang/{locale}', [LanguageController::class, 'switch'])->name('lang.switch');
    Route::get('lang/translations/{locale?}', [LanguageController::class, 'translations'])->name('lang.translations');

    // Authenticated admin routes
    Route::middleware('auth.admin')->group(function () {
        Route::post('logout', [LoginController::class, 'logout'])->name('logout');
        Route::get('/', [DashboardController::class, 'index'])->name('home');
        Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');

        // All 50 module routes generated by `php artisan erp:generate`.
        require __DIR__.'/admin_modules.php';
    });
});
