<?php

namespace App\Support;

/**
 * Central definition of every CRUD module in the ERP. Models, controllers,
 * Livewire components, views, routes and permission seeders are all generated
 * (and rendered) from this single source of truth.
 *
 * Each entry:
 *  - 'table'          : DB table name
 *  - 'model'          : App\Models\X class (basename)
 *  - 'route'          : kebab route segment (admin.{route})
 *  - 'permission_key' : prefix used for permissions (e.g. "branches" -> branches.view)
 *  - 'label_key'      : translation key under messages.modules.*
 *  - 'group'          : sidebar grouping
 *  - 'icon'           : bootstrap icon
 *  - 'fields'         : list of [name, type, label_key, options]
 *      type: string|text|integer|decimal|date|datetime|enum|bool|foreign|json
 *  - 'searchable'     : columns Yajra will allow text search on
 *  - 'belongs_to'     : ['relationName' => 'App\Models\Other']
 *  - 'has_many'       : ['relationName' => ['App\Models\Other', 'foreign_key']]
 *  - 'soft_deletes'   : bool (default true if migration has it)
 */
class ModuleManifest
{
    public static function all(): array
    {
        return [
            // ----- 1. Organization -----
            'companies' => [
                'table' => 'companies', 'model' => 'Company', 'route' => 'companies',
                'permission_key' => 'companies', 'label_key' => 'modules.companies',
                'group' => 'organization', 'icon' => 'bi-building', 'soft_deletes' => true,
                'fields' => [
                    ['name', 'string', 'common.name', ['required' => true]],
                    ['code', 'string', 'common.code', ['required' => true, 'unique' => true]],
                    ['phone', 'string', 'common.phone'],
                    ['email', 'string', 'common.email'],
                    ['address', 'text', 'common.address'],
                    ['website', 'string', 'common.reference'],
                    ['logo', 'string', 'common.reference'],
                    ['registration_no', 'string', 'common.code'],
                    ['tax_no', 'string', 'common.code'],
                    ['license_no', 'string', 'common.code'],
                    ['status', 'enum', 'common.status', ['options' => ['active', 'inactive'], 'default' => 'active']],
                ],
                'searchable' => ['name', 'code', 'email', 'phone'],
            ],
            'branches' => [
                'table' => 'branches', 'model' => 'Branch', 'route' => 'branches',
                'permission_key' => 'branches', 'label_key' => 'modules.branches',
                'group' => 'organization', 'icon' => 'bi-shop', 'soft_deletes' => true,
                'fields' => [
                    ['company_id', 'foreign', 'common.company', ['model' => 'Company', 'required' => true, 'display' => 'name']],
                    ['name', 'string', 'common.name', ['required' => true]],
                    ['code', 'string', 'common.code', ['required' => true, 'unique' => true]],
                    ['phone', 'string', 'common.phone'],
                    ['email', 'string', 'common.email'],
                    ['address', 'text', 'common.address'],
                    ['manager_id', 'foreign', 'modules.users', ['model' => 'User', 'display' => 'name']],
                    ['status', 'enum', 'common.status', ['options' => ['active', 'inactive'], 'default' => 'active']],
                ],
                'searchable' => ['name', 'code', 'email', 'phone'],
                'belongs_to' => ['company' => 'Company', 'manager' => ['User', 'manager_id']],
            ],
            'users' => [
                'table' => 'users', 'model' => 'User', 'route' => 'users',
                'permission_key' => 'users', 'label_key' => 'modules.users',
                'group' => 'organization', 'icon' => 'bi-people', 'soft_deletes' => true,
                'fields' => [
                    ['company_id', 'foreign', 'common.company', ['model' => 'Company', 'display' => 'name']],
                    ['branch_id', 'foreign', 'common.branch', ['model' => 'Branch', 'display' => 'name']],
                    ['name', 'string', 'common.name', ['required' => true]],
                    ['username', 'string', 'common.username', ['required' => true, 'unique' => true]],
                    ['email', 'string', 'common.email', ['unique' => true]],
                    ['phone', 'string', 'common.phone'],
                    ['password', 'password', 'common.password', ['required_on_create' => true]],
                    ['staff_code', 'string', 'common.code', ['unique' => true]],
                    ['position', 'string', 'common.note'],
                    ['avatar', 'string', 'common.reference'],
                    ['status', 'enum', 'common.status', ['options' => ['active', 'inactive', 'blocked'], 'default' => 'active']],
                    ['last_login_at', 'datetime', 'common.date', ['read_only' => true]],
                    ['roles', 'json', 'modules.roles', ['multi_select_model' => 'Role', 'display' => 'display_name', 'pivot' => 'role_user']],
                ],
                'searchable' => ['name', 'username', 'email', 'phone', 'staff_code'],
                'belongs_to' => ['company' => 'Company', 'branch' => 'Branch'],
            ],
            'roles' => [
                'table' => 'roles', 'model' => 'Role', 'route' => 'roles',
                'permission_key' => 'roles', 'label_key' => 'modules.roles',
                'group' => 'organization', 'icon' => 'bi-shield-lock', 'soft_deletes' => false,
                'fields' => [
                    ['name', 'string', 'common.name', ['required' => true, 'unique' => true]],
                    ['display_name', 'string', 'common.name', ['required' => true]],
                    ['description', 'text', 'common.description'],
                    ['status', 'enum', 'common.status', ['options' => ['active', 'inactive'], 'default' => 'active']],
                    ['permissions', 'json', 'modules.permissions', ['multi_select_model' => 'Permission', 'display' => 'display_name', 'pivot' => 'permission_role']],
                ],
                'searchable' => ['name', 'display_name'],
            ],
            'permissions' => [
                'table' => 'permissions', 'model' => 'Permission', 'route' => 'permissions',
                'permission_key' => 'permissions', 'label_key' => 'modules.permissions',
                'group' => 'organization', 'icon' => 'bi-key', 'soft_deletes' => false,
                'fields' => [
                    ['name', 'string', 'common.code', ['required' => true, 'unique' => true]],
                    ['module', 'string', 'common.note', ['required' => true]],
                    ['display_name', 'string', 'common.name', ['required' => true]],
                ],
                'searchable' => ['name', 'module', 'display_name'],
            ],

            // ----- 2. CRM -----
            'customers' => [
                'table' => 'customers', 'model' => 'Customer', 'route' => 'customers',
                'permission_key' => 'customers', 'label_key' => 'modules.customers',
                'group' => 'crm', 'icon' => 'bi-person-vcard', 'soft_deletes' => true,
                'fields' => [
                    ['company_id', 'foreign', 'common.company', ['model' => 'Company', 'required' => true, 'display' => 'name']],
                    ['branch_id', 'foreign', 'common.branch', ['model' => 'Branch', 'display' => 'name']],
                    ['customer_code', 'string', 'common.code', ['required' => true, 'unique' => true, 'auto' => true]],
                    ['name', 'string', 'common.name', ['required' => true]],
                    ['gender', 'enum', 'common.status', ['options' => ['male', 'female', 'other']]],
                    ['dob', 'date', 'common.date'],
                    ['phone', 'string', 'common.phone'],
                    ['email', 'string', 'common.email'],
                    ['national_id', 'string', 'common.code'],
                    ['address', 'text', 'common.address'],
                    ['occupation', 'string', 'common.note'],
                    ['company_name', 'string', 'common.company'],
                    ['source', 'string', 'common.reference'],
                    ['customer_type', 'enum', 'common.note', ['options' => ['buyer', 'renter', 'investor', 'owner'], 'default' => 'buyer']],
                    ['status', 'enum', 'common.status', ['options' => ['active', 'inactive', 'blocked'], 'default' => 'active']],
                ],
                'searchable' => ['name', 'customer_code', 'phone', 'email', 'national_id'],
                'belongs_to' => ['company' => 'Company', 'branch' => 'Branch'],
            ],
            'leads' => [
                'table' => 'leads', 'model' => 'Lead', 'route' => 'leads',
                'permission_key' => 'leads', 'label_key' => 'modules.leads',
                'group' => 'crm', 'icon' => 'bi-megaphone', 'soft_deletes' => true,
                'fields' => [
                    ['company_id', 'foreign', 'common.company', ['model' => 'Company', 'required' => true, 'display' => 'name']],
                    ['branch_id', 'foreign', 'common.branch', ['model' => 'Branch', 'display' => 'name']],
                    ['customer_id', 'foreign', 'modules.customers', ['model' => 'Customer', 'display' => 'name']],
                    ['lead_no', 'string', 'common.code', ['required' => true, 'unique' => true, 'auto' => true]],
                    ['name', 'string', 'common.name', ['required' => true]],
                    ['phone', 'string', 'common.phone'],
                    ['email', 'string', 'common.email'],
                    ['source', 'string', 'common.reference'],
                    ['interested_property_type', 'string', 'common.note'],
                    ['budget_min', 'decimal', 'common.amount'],
                    ['budget_max', 'decimal', 'common.amount'],
                    ['note', 'text', 'common.note'],
                    ['assigned_to', 'foreign', 'modules.users', ['model' => 'User', 'display' => 'name']],
                    ['status', 'enum', 'common.status', ['options' => ['new', 'contacted', 'follow_up', 'interested', 'converted', 'lost'], 'default' => 'new']],
                    ['next_follow_up_at', 'datetime', 'common.date'],
                    ['converted_at', 'datetime', 'common.date', ['read_only' => true]],
                ],
                'searchable' => ['name', 'lead_no', 'phone', 'email'],
                'belongs_to' => ['company' => 'Company', 'branch' => 'Branch', 'customer' => 'Customer', 'assignee' => ['User', 'assigned_to']],
            ],
            'lead_activities' => [
                'table' => 'lead_activities', 'model' => 'LeadActivity', 'route' => 'lead-activities',
                'permission_key' => 'lead_activities', 'label_key' => 'modules.lead_activities',
                'group' => 'crm', 'icon' => 'bi-chat-square-text', 'soft_deletes' => false,
                'fields' => [
                    ['lead_id', 'foreign', 'modules.leads', ['model' => 'Lead', 'required' => true, 'display' => 'name']],
                    ['activity_type', 'enum', 'common.note', ['options' => ['call', 'message', 'meeting', 'site_visit', 'note'], 'required' => true]],
                    ['description', 'text', 'common.description'],
                    ['activity_at', 'datetime', 'common.date', ['required' => true]],
                    ['next_follow_up_at', 'datetime', 'common.date'],
                    ['created_by', 'foreign', 'modules.users', ['model' => 'User', 'display' => 'name', 'auto_user' => true]],
                ],
                'searchable' => ['description', 'activity_type'],
                'belongs_to' => ['lead' => 'Lead', 'creator' => ['User', 'created_by']],
            ],

            // ----- 3. Property -----
            'projects' => [
                'table' => 'projects', 'model' => 'Project', 'route' => 'projects',
                'permission_key' => 'projects', 'label_key' => 'modules.projects',
                'group' => 'property', 'icon' => 'bi-diagram-3', 'soft_deletes' => true,
                'fields' => [
                    ['company_id', 'foreign', 'common.company', ['model' => 'Company', 'required' => true, 'display' => 'name']],
                    ['branch_id', 'foreign', 'common.branch', ['model' => 'Branch', 'display' => 'name']],
                    ['project_code', 'string', 'common.code', ['required' => true, 'unique' => true, 'auto' => true]],
                    ['name', 'string', 'common.name', ['required' => true]],
                    ['project_type', 'enum', 'common.note', ['options' => ['borey', 'condo', 'land', 'commercial', 'mixed_use'], 'default' => 'land']],
                    ['description', 'text', 'common.description'],
                    ['location', 'text', 'common.address'],
                    ['province', 'string', 'common.address'],
                    ['district', 'string', 'common.address'],
                    ['commune', 'string', 'common.address'],
                    ['village', 'string', 'common.address'],
                    ['latitude', 'decimal', 'common.note'],
                    ['longitude', 'decimal', 'common.note'],
                    ['start_date', 'date', 'common.date'],
                    ['expected_finish_date', 'date', 'common.date'],
                    ['actual_finish_date', 'date', 'common.date'],
                    ['total_units', 'integer', 'common.amount', ['default' => 0]],
                    ['status', 'enum', 'common.status', ['options' => ['planning', 'active', 'completed', 'suspended', 'cancelled'], 'default' => 'planning']],
                    ['created_by', 'foreign', 'modules.users', ['model' => 'User', 'display' => 'name', 'auto_user' => true]],
                ],
                'searchable' => ['name', 'project_code', 'province'],
                'belongs_to' => ['company' => 'Company', 'branch' => 'Branch', 'creator' => ['User', 'created_by']],
            ],
            'project_phases' => [
                'table' => 'project_phases', 'model' => 'ProjectPhase', 'route' => 'project-phases',
                'permission_key' => 'project_phases', 'label_key' => 'modules.project_phases',
                'group' => 'property', 'icon' => 'bi-bar-chart-steps', 'soft_deletes' => true,
                'fields' => [
                    ['project_id', 'foreign', 'modules.projects', ['model' => 'Project', 'required' => true, 'display' => 'name']],
                    ['phase_code', 'string', 'common.code'],
                    ['name', 'string', 'common.name', ['required' => true]],
                    ['description', 'text', 'common.description'],
                    ['start_date', 'date', 'common.date'],
                    ['end_date', 'date', 'common.date'],
                    ['status', 'enum', 'common.status', ['options' => ['planning', 'active', 'completed', 'cancelled'], 'default' => 'planning']],
                ],
                'searchable' => ['name', 'phase_code'],
                'belongs_to' => ['project' => 'Project'],
            ],
            'property_types' => [
                'table' => 'property_types', 'model' => 'PropertyType', 'route' => 'property-types',
                'permission_key' => 'property_types', 'label_key' => 'modules.property_types',
                'group' => 'property', 'icon' => 'bi-tags', 'soft_deletes' => true,
                'fields' => [
                    ['name', 'string', 'common.name', ['required' => true]],
                    ['code', 'string', 'common.code', ['unique' => true]],
                    ['description', 'text', 'common.description'],
                    ['status', 'enum', 'common.status', ['options' => ['active', 'inactive'], 'default' => 'active']],
                ],
                'searchable' => ['name', 'code'],
            ],
            'properties' => [
                'table' => 'properties', 'model' => 'Property', 'route' => 'properties',
                'permission_key' => 'properties', 'label_key' => 'modules.properties',
                'group' => 'property', 'icon' => 'bi-house', 'soft_deletes' => true,
                'fields' => [
                    ['company_id', 'foreign', 'common.company', ['model' => 'Company', 'required' => true, 'display' => 'name']],
                    ['branch_id', 'foreign', 'common.branch', ['model' => 'Branch', 'display' => 'name']],
                    ['project_id', 'foreign', 'modules.projects', ['model' => 'Project', 'display' => 'name']],
                    ['project_phase_id', 'foreign', 'modules.project_phases', ['model' => 'ProjectPhase', 'display' => 'name']],
                    ['property_type_id', 'foreign', 'modules.property_types', ['model' => 'PropertyType', 'required' => true, 'display' => 'name']],
                    ['owner_id', 'foreign', 'modules.customers', ['model' => 'Customer', 'display' => 'name']],
                    ['property_code', 'string', 'common.code', ['required' => true, 'unique' => true, 'auto' => true]],
                    ['title', 'string', 'common.name', ['required' => true]],
                    ['description', 'text', 'common.description'],
                    ['unit_no', 'string', 'common.code'],
                    ['floor_no', 'string', 'common.code'],
                    ['block_no', 'string', 'common.code'],
                    ['street_no', 'string', 'common.address'],
                    ['size_width', 'decimal', 'common.amount'],
                    ['size_length', 'decimal', 'common.amount'],
                    ['land_area', 'decimal', 'common.amount'],
                    ['building_area', 'decimal', 'common.amount'],
                    ['bedrooms', 'integer', 'common.amount'],
                    ['bathrooms', 'integer', 'common.amount'],
                    ['direction', 'string', 'common.note'],
                    ['hard_title_no', 'string', 'common.code'],
                    ['soft_title_no', 'string', 'common.code'],
                    ['base_price', 'decimal', 'common.amount', ['default' => 0]],
                    ['sale_price', 'decimal', 'common.amount', ['default' => 0]],
                    ['rent_price', 'decimal', 'common.amount', ['default' => 0]],
                    ['currency', 'string', 'common.currency', ['default' => 'USD']],
                    ['status', 'enum', 'common.status', ['options' => ['available', 'reserved', 'sold', 'rented', 'inactive', 'blocked'], 'default' => 'available']],
                    ['created_by', 'foreign', 'modules.users', ['model' => 'User', 'display' => 'name', 'auto_user' => true]],
                ],
                'searchable' => ['title', 'property_code', 'unit_no', 'block_no'],
                'belongs_to' => [
                    'company' => 'Company', 'branch' => 'Branch', 'project' => 'Project',
                    'phase' => ['ProjectPhase', 'project_phase_id'], 'type' => ['PropertyType', 'property_type_id'],
                    'owner' => ['Customer', 'owner_id'], 'creator' => ['User', 'created_by'],
                ],
            ],
            'property_images' => [
                'table' => 'property_images', 'model' => 'PropertyImage', 'route' => 'property-images',
                'permission_key' => 'property_images', 'label_key' => 'modules.property_images',
                'group' => 'property', 'icon' => 'bi-images', 'soft_deletes' => false,
                'fields' => [
                    ['property_id', 'foreign', 'modules.properties', ['model' => 'Property', 'required' => true, 'display' => 'title']],
                    ['image_path', 'string', 'common.reference', ['required' => true]],
                    ['caption', 'string', 'common.note'],
                    ['is_primary', 'bool', 'common.status', ['default' => false]],
                    ['sort_order', 'integer', 'common.amount', ['default' => 0]],
                ],
                'searchable' => ['caption'],
                'belongs_to' => ['property' => 'Property'],
            ],
            'property_documents' => [
                'table' => 'property_documents', 'model' => 'PropertyDocument', 'route' => 'property-documents',
                'permission_key' => 'property_documents', 'label_key' => 'modules.property_documents',
                'group' => 'property', 'icon' => 'bi-file-earmark-text', 'soft_deletes' => true,
                'fields' => [
                    ['property_id', 'foreign', 'modules.properties', ['model' => 'Property', 'required' => true, 'display' => 'title']],
                    ['document_type', 'string', 'common.note', ['required' => true]],
                    ['document_no', 'string', 'common.code'],
                    ['file_path', 'string', 'common.reference', ['required' => true]],
                    ['issue_date', 'date', 'common.date'],
                    ['expiry_date', 'date', 'common.date'],
                    ['note', 'text', 'common.note'],
                    ['uploaded_by', 'foreign', 'modules.users', ['model' => 'User', 'display' => 'name', 'auto_user' => true]],
                ],
                'searchable' => ['document_type', 'document_no'],
                'belongs_to' => ['property' => 'Property', 'uploader' => ['User', 'uploaded_by']],
            ],
            'land_parcels' => [
                'table' => 'land_parcels', 'model' => 'LandParcel', 'route' => 'land-parcels',
                'permission_key' => 'land_parcels', 'label_key' => 'modules.land_parcels',
                'group' => 'property', 'icon' => 'bi-geo-alt', 'soft_deletes' => true,
                'fields' => [
                    ['company_id', 'foreign', 'common.company', ['model' => 'Company', 'required' => true, 'display' => 'name']],
                    ['branch_id', 'foreign', 'common.branch', ['model' => 'Branch', 'display' => 'name']],
                    ['project_id', 'foreign', 'modules.projects', ['model' => 'Project', 'display' => 'name']],
                    ['parcel_code', 'string', 'common.code', ['required' => true, 'unique' => true, 'auto' => true]],
                    ['title_no', 'string', 'common.code'],
                    ['location', 'text', 'common.address'],
                    ['province', 'string', 'common.address'],
                    ['district', 'string', 'common.address'],
                    ['commune', 'string', 'common.address'],
                    ['village', 'string', 'common.address'],
                    ['total_area', 'decimal', 'common.amount', ['default' => 0]],
                    ['purchase_price', 'decimal', 'common.amount', ['default' => 0]],
                    ['purchase_date', 'date', 'common.date'],
                    ['owner_name', 'string', 'common.name'],
                    ['status', 'enum', 'common.status', ['options' => ['owned', 'developing', 'subdivided', 'sold', 'inactive'], 'default' => 'owned']],
                    ['created_by', 'foreign', 'modules.users', ['model' => 'User', 'display' => 'name', 'auto_user' => true]],
                ],
                'searchable' => ['parcel_code', 'title_no', 'province'],
                'belongs_to' => ['company' => 'Company', 'branch' => 'Branch', 'project' => 'Project', 'creator' => ['User', 'created_by']],
            ],

            // ----- 4. Sale -----
            'bookings' => [
                'table' => 'bookings', 'model' => 'Booking', 'route' => 'bookings',
                'permission_key' => 'bookings', 'label_key' => 'modules.bookings',
                'group' => 'sale', 'icon' => 'bi-bookmark-check', 'soft_deletes' => true,
                'fields' => [
                    ['company_id', 'foreign', 'common.company', ['model' => 'Company', 'required' => true, 'display' => 'name']],
                    ['branch_id', 'foreign', 'common.branch', ['model' => 'Branch', 'required' => true, 'display' => 'name']],
                    ['customer_id', 'foreign', 'modules.customers', ['model' => 'Customer', 'required' => true, 'display' => 'name']],
                    ['property_id', 'foreign', 'modules.properties', ['model' => 'Property', 'required' => true, 'display' => 'title']],
                    ['booking_no', 'string', 'common.code', ['required' => true, 'unique' => true, 'auto' => true]],
                    ['booking_date', 'datetime', 'common.date', ['required' => true]],
                    ['expiry_date', 'date', 'common.date'],
                    ['booking_amount', 'decimal', 'common.amount', ['default' => 0]],
                    ['currency', 'string', 'common.currency', ['default' => 'USD']],
                    ['note', 'text', 'common.note'],
                    ['status', 'enum', 'common.status', ['options' => ['pending', 'active', 'converted', 'cancelled', 'expired', 'refunded'], 'default' => 'pending']],
                    ['created_by', 'foreign', 'modules.users', ['model' => 'User', 'display' => 'name', 'auto_user' => true]],
                    ['cancelled_by', 'foreign', 'modules.users', ['model' => 'User', 'display' => 'name', 'read_only' => true]],
                    ['cancelled_at', 'datetime', 'common.date', ['read_only' => true]],
                ],
                'searchable' => ['booking_no'],
                'belongs_to' => ['company' => 'Company', 'branch' => 'Branch', 'customer' => 'Customer', 'property' => 'Property', 'creator' => ['User', 'created_by'], 'canceller' => ['User', 'cancelled_by']],
            ],
            'sale_contracts' => [
                'table' => 'sale_contracts', 'model' => 'SaleContract', 'route' => 'sale-contracts',
                'permission_key' => 'sale_contracts', 'label_key' => 'modules.sale_contracts',
                'group' => 'sale', 'icon' => 'bi-file-earmark-ruled', 'soft_deletes' => true,
                'fields' => [
                    ['company_id', 'foreign', 'common.company', ['model' => 'Company', 'required' => true, 'display' => 'name']],
                    ['branch_id', 'foreign', 'common.branch', ['model' => 'Branch', 'required' => true, 'display' => 'name']],
                    ['customer_id', 'foreign', 'modules.customers', ['model' => 'Customer', 'required' => true, 'display' => 'name']],
                    ['property_id', 'foreign', 'modules.properties', ['model' => 'Property', 'required' => true, 'display' => 'title']],
                    ['booking_id', 'foreign', 'modules.bookings', ['model' => 'Booking', 'display' => 'booking_no']],
                    ['contract_no', 'string', 'common.code', ['required' => true, 'unique' => true, 'auto' => true]],
                    ['contract_date', 'date', 'common.date', ['required' => true]],
                    ['sale_price', 'decimal', 'common.amount', ['default' => 0]],
                    ['discount_amount', 'decimal', 'common.amount', ['default' => 0]],
                    ['tax_amount', 'decimal', 'common.amount', ['default' => 0]],
                    ['total_amount', 'decimal', 'common.amount', ['default' => 0]],
                    ['deposit_amount', 'decimal', 'common.amount', ['default' => 0]],
                    ['paid_amount', 'decimal', 'common.amount', ['default' => 0]],
                    ['balance_amount', 'decimal', 'common.amount', ['default' => 0]],
                    ['payment_type', 'enum', 'common.note', ['options' => ['full_payment', 'installment', 'bank_loan'], 'default' => 'full_payment']],
                    ['handover_date', 'date', 'common.date'],
                    ['title_transfer_date', 'date', 'common.date'],
                    ['note', 'text', 'common.note'],
                    ['status', 'enum', 'common.status', ['options' => ['draft', 'pending_approval', 'approved', 'active', 'completed', 'cancelled', 'defaulted'], 'default' => 'draft']],
                    ['created_by', 'foreign', 'modules.users', ['model' => 'User', 'display' => 'name', 'auto_user' => true]],
                    ['approved_by', 'foreign', 'modules.users', ['model' => 'User', 'display' => 'name', 'read_only' => true]],
                    ['approved_at', 'datetime', 'common.date', ['read_only' => true]],
                ],
                'searchable' => ['contract_no'],
                'belongs_to' => ['company' => 'Company', 'branch' => 'Branch', 'customer' => 'Customer', 'property' => 'Property', 'booking' => 'Booking', 'creator' => ['User', 'created_by'], 'approver' => ['User', 'approved_by']],
            ],
            'sale_contract_items' => [
                'table' => 'sale_contract_items', 'model' => 'SaleContractItem', 'route' => 'sale-contract-items',
                'permission_key' => 'sale_contract_items', 'label_key' => 'modules.sale_contract_items',
                'group' => 'sale', 'icon' => 'bi-list-ul', 'soft_deletes' => false,
                'fields' => [
                    ['sale_contract_id', 'foreign', 'modules.sale_contracts', ['model' => 'SaleContract', 'required' => true, 'display' => 'contract_no']],
                    ['property_id', 'foreign', 'modules.properties', ['model' => 'Property', 'required' => true, 'display' => 'title']],
                    ['price', 'decimal', 'common.amount', ['default' => 0]],
                    ['discount_amount', 'decimal', 'common.amount', ['default' => 0]],
                    ['total_amount', 'decimal', 'common.amount', ['default' => 0]],
                ],
                'searchable' => [],
                'belongs_to' => ['contract' => ['SaleContract', 'sale_contract_id'], 'property' => 'Property'],
            ],
            'installment_schedules' => [
                'table' => 'installment_schedules', 'model' => 'InstallmentSchedule', 'route' => 'installment-schedules',
                'permission_key' => 'installment_schedules', 'label_key' => 'modules.installment_schedules',
                'group' => 'sale', 'icon' => 'bi-calendar3', 'soft_deletes' => false,
                'fields' => [
                    ['sale_contract_id', 'foreign', 'modules.sale_contracts', ['model' => 'SaleContract', 'required' => true, 'display' => 'contract_no']],
                    ['installment_no', 'integer', 'common.amount', ['required' => true]],
                    ['due_date', 'date', 'common.date', ['required' => true]],
                    ['principal_amount', 'decimal', 'common.amount', ['default' => 0]],
                    ['interest_amount', 'decimal', 'common.amount', ['default' => 0]],
                    ['penalty_amount', 'decimal', 'common.amount', ['default' => 0]],
                    ['total_amount', 'decimal', 'common.amount', ['default' => 0]],
                    ['paid_amount', 'decimal', 'common.amount', ['default' => 0]],
                    ['balance_amount', 'decimal', 'common.amount', ['default' => 0]],
                    ['status', 'enum', 'common.status', ['options' => ['unpaid', 'partial_paid', 'paid', 'overdue', 'waived'], 'default' => 'unpaid']],
                    ['paid_at', 'datetime', 'common.date'],
                ],
                'searchable' => [],
                'belongs_to' => ['contract' => ['SaleContract', 'sale_contract_id']],
            ],

            // ----- 5. Invoice / Payment -----
            'payment_methods' => [
                'table' => 'payment_methods', 'model' => 'PaymentMethod', 'route' => 'payment-methods',
                'permission_key' => 'payment_methods', 'label_key' => 'modules.payment_methods',
                'group' => 'invoice', 'icon' => 'bi-credit-card', 'soft_deletes' => false,
                'fields' => [
                    ['name', 'string', 'common.name', ['required' => true]],
                    ['code', 'string', 'common.code', ['required' => true, 'unique' => true]],
                    ['account_name', 'string', 'common.name'],
                    ['account_no', 'string', 'common.code'],
                    ['status', 'enum', 'common.status', ['options' => ['active', 'inactive'], 'default' => 'active']],
                ],
                'searchable' => ['name', 'code'],
            ],
            'invoices' => [
                'table' => 'invoices', 'model' => 'Invoice', 'route' => 'invoices',
                'permission_key' => 'invoices', 'label_key' => 'modules.invoices',
                'group' => 'invoice', 'icon' => 'bi-receipt', 'soft_deletes' => true,
                'fields' => [
                    ['company_id', 'foreign', 'common.company', ['model' => 'Company', 'required' => true, 'display' => 'name']],
                    ['branch_id', 'foreign', 'common.branch', ['model' => 'Branch', 'required' => true, 'display' => 'name']],
                    ['customer_id', 'foreign', 'modules.customers', ['model' => 'Customer', 'required' => true, 'display' => 'name']],
                    ['invoice_no', 'string', 'common.code', ['required' => true, 'unique' => true, 'auto' => true]],
                    ['invoice_type', 'enum', 'common.note', ['options' => ['booking', 'sale', 'installment', 'rental', 'service'], 'default' => 'sale']],
                    ['invoiceable_type', 'string', 'common.note'],
                    ['invoiceable_id', 'integer', 'common.note'],
                    ['invoice_date', 'date', 'common.date', ['required' => true]],
                    ['due_date', 'date', 'common.date'],
                    ['subtotal', 'decimal', 'common.amount', ['default' => 0]],
                    ['discount_amount', 'decimal', 'common.amount', ['default' => 0]],
                    ['tax_amount', 'decimal', 'common.amount', ['default' => 0]],
                    ['total_amount', 'decimal', 'common.amount', ['default' => 0]],
                    ['paid_amount', 'decimal', 'common.amount', ['default' => 0]],
                    ['balance_amount', 'decimal', 'common.amount', ['default' => 0]],
                    ['status', 'enum', 'common.status', ['options' => ['draft', 'unpaid', 'partial_paid', 'paid', 'cancelled', 'refunded'], 'default' => 'draft']],
                    ['created_by', 'foreign', 'modules.users', ['model' => 'User', 'display' => 'name', 'auto_user' => true]],
                ],
                'searchable' => ['invoice_no'],
                'belongs_to' => ['company' => 'Company', 'branch' => 'Branch', 'customer' => 'Customer', 'creator' => ['User', 'created_by']],
            ],
            'invoice_items' => [
                'table' => 'invoice_items', 'model' => 'InvoiceItem', 'route' => 'invoice-items',
                'permission_key' => 'invoice_items', 'label_key' => 'modules.invoice_items',
                'group' => 'invoice', 'icon' => 'bi-receipt-cutoff', 'soft_deletes' => false,
                'fields' => [
                    ['invoice_id', 'foreign', 'modules.invoices', ['model' => 'Invoice', 'required' => true, 'display' => 'invoice_no']],
                    ['description', 'string', 'common.description', ['required' => true]],
                    ['quantity', 'decimal', 'common.amount', ['default' => 1]],
                    ['unit_price', 'decimal', 'common.amount', ['default' => 0]],
                    ['discount_amount', 'decimal', 'common.amount', ['default' => 0]],
                    ['tax_amount', 'decimal', 'common.amount', ['default' => 0]],
                    ['total_amount', 'decimal', 'common.amount', ['default' => 0]],
                ],
                'searchable' => ['description'],
                'belongs_to' => ['invoice' => 'Invoice'],
            ],
            'payments' => [
                'table' => 'payments', 'model' => 'Payment', 'route' => 'payments',
                'permission_key' => 'payments', 'label_key' => 'modules.payments',
                'group' => 'invoice', 'icon' => 'bi-cash-coin', 'soft_deletes' => true,
                'fields' => [
                    ['company_id', 'foreign', 'common.company', ['model' => 'Company', 'required' => true, 'display' => 'name']],
                    ['branch_id', 'foreign', 'common.branch', ['model' => 'Branch', 'required' => true, 'display' => 'name']],
                    ['customer_id', 'foreign', 'modules.customers', ['model' => 'Customer', 'display' => 'name']],
                    ['invoice_id', 'foreign', 'modules.invoices', ['model' => 'Invoice', 'display' => 'invoice_no']],
                    ['sale_contract_id', 'foreign', 'modules.sale_contracts', ['model' => 'SaleContract', 'display' => 'contract_no']],
                    ['booking_id', 'foreign', 'modules.bookings', ['model' => 'Booking', 'display' => 'booking_no']],
                    ['payment_no', 'string', 'common.code', ['required' => true, 'unique' => true, 'auto' => true]],
                    ['payment_method_id', 'foreign', 'modules.payment_methods', ['model' => 'PaymentMethod', 'required' => true, 'display' => 'name']],
                    ['payment_date', 'datetime', 'common.date', ['required' => true]],
                    ['amount', 'decimal', 'common.amount', ['required' => true]],
                    ['currency', 'string', 'common.currency', ['default' => 'USD']],
                    ['reference_no', 'string', 'common.reference'],
                    ['note', 'text', 'common.note'],
                    ['status', 'enum', 'common.status', ['options' => ['pending', 'paid', 'failed', 'refunded', 'cancelled'], 'default' => 'paid']],
                    ['received_by', 'foreign', 'modules.users', ['model' => 'User', 'display' => 'name']],
                ],
                'searchable' => ['payment_no', 'reference_no'],
                'belongs_to' => ['company' => 'Company', 'branch' => 'Branch', 'customer' => 'Customer', 'invoice' => 'Invoice', 'contract' => ['SaleContract', 'sale_contract_id'], 'booking' => 'Booking', 'method' => ['PaymentMethod', 'payment_method_id'], 'receiver' => ['User', 'received_by']],
            ],
            'payment_allocations' => [
                'table' => 'payment_allocations', 'model' => 'PaymentAllocation', 'route' => 'payment-allocations',
                'permission_key' => 'payment_allocations', 'label_key' => 'modules.payment_allocations',
                'group' => 'invoice', 'icon' => 'bi-diagram-2', 'soft_deletes' => false,
                'fields' => [
                    ['payment_id', 'foreign', 'modules.payments', ['model' => 'Payment', 'required' => true, 'display' => 'payment_no']],
                    ['installment_schedule_id', 'foreign', 'modules.installment_schedules', ['model' => 'InstallmentSchedule', 'display' => 'installment_no']],
                    ['invoice_id', 'foreign', 'modules.invoices', ['model' => 'Invoice', 'display' => 'invoice_no']],
                    ['amount', 'decimal', 'common.amount', ['default' => 0]],
                ],
                'searchable' => [],
                'belongs_to' => ['payment' => 'Payment', 'installment' => ['InstallmentSchedule', 'installment_schedule_id'], 'invoice' => 'Invoice'],
            ],
            'refunds' => [
                'table' => 'refunds', 'model' => 'Refund', 'route' => 'refunds',
                'permission_key' => 'refunds', 'label_key' => 'modules.refunds',
                'group' => 'invoice', 'icon' => 'bi-arrow-counterclockwise', 'soft_deletes' => true,
                'fields' => [
                    ['company_id', 'foreign', 'common.company', ['model' => 'Company', 'required' => true, 'display' => 'name']],
                    ['branch_id', 'foreign', 'common.branch', ['model' => 'Branch', 'required' => true, 'display' => 'name']],
                    ['customer_id', 'foreign', 'modules.customers', ['model' => 'Customer', 'required' => true, 'display' => 'name']],
                    ['payment_id', 'foreign', 'modules.payments', ['model' => 'Payment', 'display' => 'payment_no']],
                    ['refund_no', 'string', 'common.code', ['required' => true, 'unique' => true, 'auto' => true]],
                    ['refund_date', 'datetime', 'common.date', ['required' => true]],
                    ['amount', 'decimal', 'common.amount', ['required' => true]],
                    ['reason', 'text', 'common.note', ['required' => true]],
                    ['status', 'enum', 'common.status', ['options' => ['requested', 'approved', 'refunded', 'rejected', 'cancelled'], 'default' => 'requested']],
                    ['requested_by', 'foreign', 'modules.users', ['model' => 'User', 'display' => 'name', 'auto_user' => true]],
                    ['approved_by', 'foreign', 'modules.users', ['model' => 'User', 'display' => 'name', 'read_only' => true]],
                    ['refunded_by', 'foreign', 'modules.users', ['model' => 'User', 'display' => 'name', 'read_only' => true]],
                ],
                'searchable' => ['refund_no'],
                'belongs_to' => ['company' => 'Company', 'branch' => 'Branch', 'customer' => 'Customer', 'payment' => 'Payment', 'requester' => ['User', 'requested_by'], 'approver' => ['User', 'approved_by'], 'refunder' => ['User', 'refunded_by']],
            ],

            // ----- 6. Rental -----
            'rental_contracts' => [
                'table' => 'rental_contracts', 'model' => 'RentalContract', 'route' => 'rental-contracts',
                'permission_key' => 'rental_contracts', 'label_key' => 'modules.rental_contracts',
                'group' => 'rental', 'icon' => 'bi-file-earmark-medical', 'soft_deletes' => true,
                'fields' => [
                    ['company_id', 'foreign', 'common.company', ['model' => 'Company', 'required' => true, 'display' => 'name']],
                    ['branch_id', 'foreign', 'common.branch', ['model' => 'Branch', 'required' => true, 'display' => 'name']],
                    ['customer_id', 'foreign', 'modules.customers', ['model' => 'Customer', 'required' => true, 'display' => 'name']],
                    ['property_id', 'foreign', 'modules.properties', ['model' => 'Property', 'required' => true, 'display' => 'title']],
                    ['contract_no', 'string', 'common.code', ['required' => true, 'unique' => true, 'auto' => true]],
                    ['start_date', 'date', 'common.date', ['required' => true]],
                    ['end_date', 'date', 'common.date', ['required' => true]],
                    ['monthly_rent', 'decimal', 'common.amount', ['default' => 0]],
                    ['deposit_amount', 'decimal', 'common.amount', ['default' => 0]],
                    ['payment_cycle', 'enum', 'common.note', ['options' => ['monthly', 'quarterly', 'yearly'], 'default' => 'monthly']],
                    ['status', 'enum', 'common.status', ['options' => ['draft', 'active', 'expired', 'terminated', 'cancelled'], 'default' => 'draft']],
                    ['created_by', 'foreign', 'modules.users', ['model' => 'User', 'display' => 'name', 'auto_user' => true]],
                    ['approved_by', 'foreign', 'modules.users', ['model' => 'User', 'display' => 'name', 'read_only' => true]],
                ],
                'searchable' => ['contract_no'],
                'belongs_to' => ['company' => 'Company', 'branch' => 'Branch', 'customer' => 'Customer', 'property' => 'Property', 'creator' => ['User', 'created_by'], 'approver' => ['User', 'approved_by']],
            ],
            'rental_invoices' => [
                'table' => 'rental_invoices', 'model' => 'RentalInvoice', 'route' => 'rental-invoices',
                'permission_key' => 'rental_invoices', 'label_key' => 'modules.rental_invoices',
                'group' => 'rental', 'icon' => 'bi-cash-stack', 'soft_deletes' => false,
                'fields' => [
                    ['rental_contract_id', 'foreign', 'modules.rental_contracts', ['model' => 'RentalContract', 'required' => true, 'display' => 'contract_no']],
                    ['invoice_id', 'foreign', 'modules.invoices', ['model' => 'Invoice', 'display' => 'invoice_no']],
                    ['rent_month', 'string', 'common.date', ['required' => true]],
                    ['due_date', 'date', 'common.date', ['required' => true]],
                    ['rent_amount', 'decimal', 'common.amount', ['default' => 0]],
                    ['penalty_amount', 'decimal', 'common.amount', ['default' => 0]],
                    ['total_amount', 'decimal', 'common.amount', ['default' => 0]],
                    ['status', 'enum', 'common.status', ['options' => ['unpaid', 'partial_paid', 'paid', 'overdue', 'cancelled'], 'default' => 'unpaid']],
                ],
                'searchable' => ['rent_month'],
                'belongs_to' => ['rental' => ['RentalContract', 'rental_contract_id'], 'invoice' => 'Invoice'],
            ],

            // ----- 7. Sales Team -----
            'sales_teams' => [
                'table' => 'sales_teams', 'model' => 'SalesTeam', 'route' => 'sales-teams',
                'permission_key' => 'sales_teams', 'label_key' => 'modules.sales_teams',
                'group' => 'sales_team', 'icon' => 'bi-people-fill', 'soft_deletes' => true,
                'fields' => [
                    ['branch_id', 'foreign', 'common.branch', ['model' => 'Branch', 'required' => true, 'display' => 'name']],
                    ['name', 'string', 'common.name', ['required' => true]],
                    ['leader_id', 'foreign', 'modules.users', ['model' => 'User', 'display' => 'name']],
                    ['status', 'enum', 'common.status', ['options' => ['active', 'inactive'], 'default' => 'active']],
                ],
                'searchable' => ['name'],
                'belongs_to' => ['branch' => 'Branch', 'leader' => ['User', 'leader_id']],
            ],
            'sales_team_members' => [
                'table' => 'sales_team_members', 'model' => 'SalesTeamMember', 'route' => 'sales-team-members',
                'permission_key' => 'sales_team_members', 'label_key' => 'modules.sales_team_members',
                'group' => 'sales_team', 'icon' => 'bi-person-plus', 'soft_deletes' => false,
                'fields' => [
                    ['sales_team_id', 'foreign', 'modules.sales_teams', ['model' => 'SalesTeam', 'required' => true, 'display' => 'name']],
                    ['user_id', 'foreign', 'modules.users', ['model' => 'User', 'required' => true, 'display' => 'name']],
                    ['role', 'enum', 'common.note', ['options' => ['leader', 'member'], 'default' => 'member']],
                    ['joined_at', 'date', 'common.date'],
                    ['status', 'enum', 'common.status', ['options' => ['active', 'inactive'], 'default' => 'active']],
                ],
                'searchable' => [],
                'belongs_to' => ['team' => ['SalesTeam', 'sales_team_id'], 'user' => 'User'],
            ],
            'commissions' => [
                'table' => 'commissions', 'model' => 'Commission', 'route' => 'commissions',
                'permission_key' => 'commissions', 'label_key' => 'modules.commissions',
                'group' => 'sales_team', 'icon' => 'bi-percent', 'soft_deletes' => true,
                'fields' => [
                    ['company_id', 'foreign', 'common.company', ['model' => 'Company', 'required' => true, 'display' => 'name']],
                    ['branch_id', 'foreign', 'common.branch', ['model' => 'Branch', 'required' => true, 'display' => 'name']],
                    ['sale_contract_id', 'foreign', 'modules.sale_contracts', ['model' => 'SaleContract', 'required' => true, 'display' => 'contract_no']],
                    ['user_id', 'foreign', 'modules.users', ['model' => 'User', 'required' => true, 'display' => 'name']],
                    ['commission_no', 'string', 'common.code', ['required' => true, 'unique' => true, 'auto' => true]],
                    ['commission_type', 'enum', 'common.note', ['options' => ['percentage', 'fixed'], 'default' => 'percentage']],
                    ['commission_rate', 'decimal', 'common.amount', ['default' => 0]],
                    ['sale_amount', 'decimal', 'common.amount', ['default' => 0]],
                    ['commission_amount', 'decimal', 'common.amount', ['default' => 0]],
                    ['status', 'enum', 'common.status', ['options' => ['pending', 'approved', 'paid', 'cancelled'], 'default' => 'pending']],
                    ['approved_by', 'foreign', 'modules.users', ['model' => 'User', 'display' => 'name', 'read_only' => true]],
                    ['paid_at', 'datetime', 'common.date', ['read_only' => true]],
                ],
                'searchable' => ['commission_no'],
                'belongs_to' => ['company' => 'Company', 'branch' => 'Branch', 'contract' => ['SaleContract', 'sale_contract_id'], 'user' => 'User', 'approver' => ['User', 'approved_by']],
            ],

            // ----- 8. Document -----
            'documents' => [
                'table' => 'documents', 'model' => 'Document', 'route' => 'documents',
                'permission_key' => 'documents', 'label_key' => 'modules.documents',
                'group' => 'document', 'icon' => 'bi-folder', 'soft_deletes' => true,
                'fields' => [
                    ['company_id', 'foreign', 'common.company', ['model' => 'Company', 'required' => true, 'display' => 'name']],
                    ['branch_id', 'foreign', 'common.branch', ['model' => 'Branch', 'display' => 'name']],
                    ['documentable_type', 'string', 'common.note', ['required' => true]],
                    ['documentable_id', 'integer', 'common.note', ['required' => true]],
                    ['document_no', 'string', 'common.code'],
                    ['document_type', 'string', 'common.note', ['required' => true]],
                    ['title', 'string', 'common.name', ['required' => true]],
                    ['file_path', 'string', 'common.reference', ['required' => true]],
                    ['version', 'string', 'common.code', ['default' => '1.0']],
                    ['issue_date', 'date', 'common.date'],
                    ['expiry_date', 'date', 'common.date'],
                    ['status', 'enum', 'common.status', ['options' => ['draft', 'active', 'expired', 'archived'], 'default' => 'active']],
                    ['uploaded_by', 'foreign', 'modules.users', ['model' => 'User', 'display' => 'name', 'auto_user' => true]],
                    ['approved_by', 'foreign', 'modules.users', ['model' => 'User', 'display' => 'name', 'read_only' => true]],
                    ['approved_at', 'datetime', 'common.date', ['read_only' => true]],
                ],
                'searchable' => ['title', 'document_no', 'document_type'],
                'belongs_to' => ['company' => 'Company', 'branch' => 'Branch', 'uploader' => ['User', 'uploaded_by'], 'approver' => ['User', 'approved_by']],
            ],

            // ----- 9. Finance -----
            'chart_of_accounts' => [
                'table' => 'chart_of_accounts', 'model' => 'ChartOfAccount', 'route' => 'chart-of-accounts',
                'permission_key' => 'chart_of_accounts', 'label_key' => 'modules.chart_of_accounts',
                'group' => 'finance', 'icon' => 'bi-bookmarks', 'soft_deletes' => true,
                'fields' => [
                    ['company_id', 'foreign', 'common.company', ['model' => 'Company', 'required' => true, 'display' => 'name']],
                    ['account_code', 'string', 'common.code', ['required' => true, 'unique' => true]],
                    ['account_name', 'string', 'common.name', ['required' => true]],
                    ['account_type', 'enum', 'common.note', ['options' => ['asset', 'liability', 'equity', 'revenue', 'expense'], 'required' => true]],
                    ['parent_id', 'foreign', 'common.note', ['model' => 'ChartOfAccount', 'display' => 'account_name']],
                    ['status', 'enum', 'common.status', ['options' => ['active', 'inactive'], 'default' => 'active']],
                ],
                'searchable' => ['account_code', 'account_name'],
                'belongs_to' => ['company' => 'Company', 'parent' => ['ChartOfAccount', 'parent_id']],
            ],
            'expense_categories' => [
                'table' => 'expense_categories', 'model' => 'ExpenseCategory', 'route' => 'expense-categories',
                'permission_key' => 'expense_categories', 'label_key' => 'modules.expense_categories',
                'group' => 'finance', 'icon' => 'bi-tags-fill', 'soft_deletes' => false,
                'fields' => [
                    ['name', 'string', 'common.name', ['required' => true]],
                    ['status', 'enum', 'common.status', ['options' => ['active', 'inactive'], 'default' => 'active']],
                ],
                'searchable' => ['name'],
            ],
            'expenses' => [
                'table' => 'expenses', 'model' => 'Expense', 'route' => 'expenses',
                'permission_key' => 'expenses', 'label_key' => 'modules.expenses',
                'group' => 'finance', 'icon' => 'bi-currency-exchange', 'soft_deletes' => true,
                'fields' => [
                    ['company_id', 'foreign', 'common.company', ['model' => 'Company', 'required' => true, 'display' => 'name']],
                    ['branch_id', 'foreign', 'common.branch', ['model' => 'Branch', 'required' => true, 'display' => 'name']],
                    ['expense_category_id', 'foreign', 'modules.expense_categories', ['model' => 'ExpenseCategory', 'required' => true, 'display' => 'name']],
                    ['expense_no', 'string', 'common.code', ['required' => true, 'unique' => true, 'auto' => true]],
                    ['expense_date', 'date', 'common.date', ['required' => true]],
                    ['amount', 'decimal', 'common.amount', ['required' => true]],
                    ['payment_method_id', 'foreign', 'modules.payment_methods', ['model' => 'PaymentMethod', 'display' => 'name']],
                    ['description', 'text', 'common.description'],
                    ['attachment', 'string', 'common.reference'],
                    ['status', 'enum', 'common.status', ['options' => ['pending', 'approved', 'paid', 'rejected'], 'default' => 'pending']],
                    ['created_by', 'foreign', 'modules.users', ['model' => 'User', 'display' => 'name', 'auto_user' => true]],
                    ['approved_by', 'foreign', 'modules.users', ['model' => 'User', 'display' => 'name', 'read_only' => true]],
                ],
                'searchable' => ['expense_no', 'description'],
                'belongs_to' => ['company' => 'Company', 'branch' => 'Branch', 'category' => ['ExpenseCategory', 'expense_category_id'], 'method' => ['PaymentMethod', 'payment_method_id'], 'creator' => ['User', 'created_by'], 'approver' => ['User', 'approved_by']],
            ],
            'journal_entries' => [
                'table' => 'journal_entries', 'model' => 'JournalEntry', 'route' => 'journal-entries',
                'permission_key' => 'journal_entries', 'label_key' => 'modules.journal_entries',
                'group' => 'finance', 'icon' => 'bi-journal-text', 'soft_deletes' => true,
                'fields' => [
                    ['company_id', 'foreign', 'common.company', ['model' => 'Company', 'required' => true, 'display' => 'name']],
                    ['branch_id', 'foreign', 'common.branch', ['model' => 'Branch', 'display' => 'name']],
                    ['entry_no', 'string', 'common.code', ['required' => true, 'unique' => true, 'auto' => true]],
                    ['entry_date', 'date', 'common.date', ['required' => true]],
                    ['reference_type', 'string', 'common.reference'],
                    ['reference_id', 'integer', 'common.reference'],
                    ['description', 'text', 'common.description'],
                    ['status', 'enum', 'common.status', ['options' => ['draft', 'posted', 'cancelled'], 'default' => 'draft']],
                    ['created_by', 'foreign', 'modules.users', ['model' => 'User', 'display' => 'name', 'auto_user' => true]],
                    ['posted_by', 'foreign', 'modules.users', ['model' => 'User', 'display' => 'name', 'read_only' => true]],
                    ['posted_at', 'datetime', 'common.date', ['read_only' => true]],
                ],
                'searchable' => ['entry_no'],
                'belongs_to' => ['company' => 'Company', 'branch' => 'Branch', 'creator' => ['User', 'created_by'], 'poster' => ['User', 'posted_by']],
            ],
            'journal_entry_items' => [
                'table' => 'journal_entry_items', 'model' => 'JournalEntryItem', 'route' => 'journal-entry-items',
                'permission_key' => 'journal_entry_items', 'label_key' => 'modules.journal_entry_items',
                'group' => 'finance', 'icon' => 'bi-list-columns', 'soft_deletes' => false,
                'fields' => [
                    ['journal_entry_id', 'foreign', 'modules.journal_entries', ['model' => 'JournalEntry', 'required' => true, 'display' => 'entry_no']],
                    ['chart_of_account_id', 'foreign', 'modules.chart_of_accounts', ['model' => 'ChartOfAccount', 'required' => true, 'display' => 'account_name']],
                    ['debit', 'decimal', 'common.amount', ['default' => 0]],
                    ['credit', 'decimal', 'common.amount', ['default' => 0]],
                    ['description', 'text', 'common.description'],
                ],
                'searchable' => ['description'],
                'belongs_to' => ['entry' => ['JournalEntry', 'journal_entry_id'], 'account' => ['ChartOfAccount', 'chart_of_account_id']],
            ],

            // ----- 10. HR / Asset -----
            'departments' => [
                'table' => 'departments', 'model' => 'Department', 'route' => 'departments',
                'permission_key' => 'departments', 'label_key' => 'modules.departments',
                'group' => 'hr_asset', 'icon' => 'bi-diagram-2-fill', 'soft_deletes' => true,
                'fields' => [
                    ['company_id', 'foreign', 'common.company', ['model' => 'Company', 'required' => true, 'display' => 'name']],
                    ['branch_id', 'foreign', 'common.branch', ['model' => 'Branch', 'display' => 'name']],
                    ['name', 'string', 'common.name', ['required' => true]],
                    ['status', 'enum', 'common.status', ['options' => ['active', 'inactive'], 'default' => 'active']],
                ],
                'searchable' => ['name'],
                'belongs_to' => ['company' => 'Company', 'branch' => 'Branch'],
            ],
            'employees' => [
                'table' => 'employees', 'model' => 'Employee', 'route' => 'employees',
                'permission_key' => 'employees', 'label_key' => 'modules.employees',
                'group' => 'hr_asset', 'icon' => 'bi-person-badge', 'soft_deletes' => true,
                'fields' => [
                    ['user_id', 'foreign', 'modules.users', ['model' => 'User', 'display' => 'name']],
                    ['company_id', 'foreign', 'common.company', ['model' => 'Company', 'required' => true, 'display' => 'name']],
                    ['branch_id', 'foreign', 'common.branch', ['model' => 'Branch', 'display' => 'name']],
                    ['department_id', 'foreign', 'modules.departments', ['model' => 'Department', 'display' => 'name']],
                    ['employee_code', 'string', 'common.code', ['required' => true, 'unique' => true, 'auto' => true]],
                    ['name', 'string', 'common.name', ['required' => true]],
                    ['gender', 'enum', 'common.status', ['options' => ['male', 'female', 'other']]],
                    ['dob', 'date', 'common.date'],
                    ['phone', 'string', 'common.phone'],
                    ['email', 'string', 'common.email'],
                    ['address', 'text', 'common.address'],
                    ['hire_date', 'date', 'common.date'],
                    ['salary', 'decimal', 'common.amount', ['default' => 0]],
                    ['status', 'enum', 'common.status', ['options' => ['active', 'resigned', 'terminated'], 'default' => 'active']],
                ],
                'searchable' => ['name', 'employee_code', 'phone', 'email'],
                'belongs_to' => ['user' => 'User', 'company' => 'Company', 'branch' => 'Branch', 'department' => 'Department'],
            ],
            'asset_categories' => [
                'table' => 'asset_categories', 'model' => 'AssetCategory', 'route' => 'asset-categories',
                'permission_key' => 'asset_categories', 'label_key' => 'modules.asset_categories',
                'group' => 'hr_asset', 'icon' => 'bi-box-seam', 'soft_deletes' => true,
                'fields' => [
                    ['name', 'string', 'common.name', ['required' => true]],
                    ['code', 'string', 'common.code', ['unique' => true]],
                    ['status', 'enum', 'common.status', ['options' => ['active', 'inactive'], 'default' => 'active']],
                ],
                'searchable' => ['name', 'code'],
            ],
            'assets' => [
                'table' => 'assets', 'model' => 'Asset', 'route' => 'assets',
                'permission_key' => 'assets', 'label_key' => 'modules.assets',
                'group' => 'hr_asset', 'icon' => 'bi-pc-display', 'soft_deletes' => true,
                'fields' => [
                    ['company_id', 'foreign', 'common.company', ['model' => 'Company', 'required' => true, 'display' => 'name']],
                    ['branch_id', 'foreign', 'common.branch', ['model' => 'Branch', 'display' => 'name']],
                    ['asset_category_id', 'foreign', 'modules.asset_categories', ['model' => 'AssetCategory', 'required' => true, 'display' => 'name']],
                    ['asset_code', 'string', 'common.code', ['required' => true, 'unique' => true, 'auto' => true]],
                    ['name', 'string', 'common.name', ['required' => true]],
                    ['serial_no', 'string', 'common.code'],
                    ['purchase_date', 'date', 'common.date'],
                    ['purchase_price', 'decimal', 'common.amount', ['default' => 0]],
                    ['assigned_to', 'foreign', 'modules.users', ['model' => 'User', 'display' => 'name']],
                    ['location', 'string', 'common.address'],
                    ['status', 'enum', 'common.status', ['options' => ['available', 'assigned', 'maintenance', 'disposed'], 'default' => 'available']],
                ],
                'searchable' => ['name', 'asset_code', 'serial_no'],
                'belongs_to' => ['company' => 'Company', 'branch' => 'Branch', 'category' => ['AssetCategory', 'asset_category_id'], 'assignee' => ['User', 'assigned_to']],
            ],

            // ----- 11. Approval / Task -----
            'approval_requests' => [
                'table' => 'approval_requests', 'model' => 'ApprovalRequest', 'route' => 'approval-requests',
                'permission_key' => 'approval_requests', 'label_key' => 'modules.approval_requests',
                'group' => 'approval', 'icon' => 'bi-check2-circle', 'soft_deletes' => true,
                'fields' => [
                    ['company_id', 'foreign', 'common.company', ['model' => 'Company', 'required' => true, 'display' => 'name']],
                    ['branch_id', 'foreign', 'common.branch', ['model' => 'Branch', 'display' => 'name']],
                    ['request_no', 'string', 'common.code', ['required' => true, 'unique' => true, 'auto' => true]],
                    ['approvable_type', 'string', 'common.note', ['required' => true]],
                    ['approvable_id', 'integer', 'common.note', ['required' => true]],
                    ['requested_by', 'foreign', 'modules.users', ['model' => 'User', 'display' => 'name', 'auto_user' => true]],
                    ['current_approver_id', 'foreign', 'modules.users', ['model' => 'User', 'display' => 'name']],
                    ['reason', 'text', 'common.note'],
                    ['status', 'enum', 'common.status', ['options' => ['pending', 'approved', 'rejected', 'cancelled'], 'default' => 'pending']],
                    ['requested_at', 'datetime', 'common.date', ['read_only' => true]],
                    ['completed_at', 'datetime', 'common.date', ['read_only' => true]],
                ],
                'searchable' => ['request_no'],
                'belongs_to' => ['company' => 'Company', 'branch' => 'Branch', 'requester' => ['User', 'requested_by'], 'currentApprover' => ['User', 'current_approver_id']],
            ],
            'approval_steps' => [
                'table' => 'approval_steps', 'model' => 'ApprovalStep', 'route' => 'approval-steps',
                'permission_key' => 'approval_steps', 'label_key' => 'modules.approval_steps',
                'group' => 'approval', 'icon' => 'bi-list-check', 'soft_deletes' => false,
                'fields' => [
                    ['approval_request_id', 'foreign', 'modules.approval_requests', ['model' => 'ApprovalRequest', 'required' => true, 'display' => 'request_no']],
                    ['step_no', 'integer', 'common.amount', ['required' => true]],
                    ['approver_id', 'foreign', 'modules.users', ['model' => 'User', 'required' => true, 'display' => 'name']],
                    ['status', 'enum', 'common.status', ['options' => ['pending', 'approved', 'rejected', 'skipped'], 'default' => 'pending']],
                    ['comment', 'text', 'common.note'],
                    ['acted_at', 'datetime', 'common.date'],
                ],
                'searchable' => [],
                'belongs_to' => ['request' => ['ApprovalRequest', 'approval_request_id'], 'approver' => ['User', 'approver_id']],
            ],
            'tasks' => [
                'table' => 'tasks', 'model' => 'Task', 'route' => 'tasks',
                'permission_key' => 'tasks', 'label_key' => 'modules.tasks',
                'group' => 'approval', 'icon' => 'bi-check2-square', 'soft_deletes' => true,
                'fields' => [
                    ['company_id', 'foreign', 'common.company', ['model' => 'Company', 'required' => true, 'display' => 'name']],
                    ['branch_id', 'foreign', 'common.branch', ['model' => 'Branch', 'display' => 'name']],
                    ['title', 'string', 'common.name', ['required' => true]],
                    ['description', 'text', 'common.description'],
                    ['taskable_type', 'string', 'common.note'],
                    ['taskable_id', 'integer', 'common.note'],
                    ['assigned_to', 'foreign', 'modules.users', ['model' => 'User', 'display' => 'name']],
                    ['priority', 'enum', 'common.note', ['options' => ['low', 'normal', 'high', 'urgent'], 'default' => 'normal']],
                    ['due_date', 'date', 'common.date'],
                    ['status', 'enum', 'common.status', ['options' => ['pending', 'in_progress', 'completed', 'cancelled'], 'default' => 'pending']],
                    ['created_by', 'foreign', 'modules.users', ['model' => 'User', 'display' => 'name', 'auto_user' => true]],
                ],
                'searchable' => ['title', 'description'],
                'belongs_to' => ['company' => 'Company', 'branch' => 'Branch', 'assignee' => ['User', 'assigned_to'], 'creator' => ['User', 'created_by']],
            ],

            // ----- 12. System -----
            'notifications' => [
                'table' => 'notifications', 'model' => 'NotificationLog', 'route' => 'notifications',
                'permission_key' => 'notifications', 'label_key' => 'modules.notifications',
                'group' => 'system', 'icon' => 'bi-bell', 'soft_deletes' => false,
                'uuid_pk' => true,
                'fields' => [
                    ['user_id', 'foreign', 'modules.users', ['model' => 'User', 'display' => 'name']],
                    ['company_id', 'foreign', 'common.company', ['model' => 'Company', 'display' => 'name']],
                    ['branch_id', 'foreign', 'common.branch', ['model' => 'Branch', 'display' => 'name']],
                    ['type', 'string', 'common.note', ['required' => true]],
                    ['title', 'string', 'common.name', ['required' => true]],
                    ['message', 'text', 'common.description', ['required' => true]],
                    ['data', 'json', 'common.note', ['read_only' => true]],
                    ['channel', 'enum', 'common.note', ['options' => ['system', 'email', 'sms', 'telegram', 'whatsapp'], 'default' => 'system']],
                    ['read_at', 'datetime', 'common.date'],
                ],
                'searchable' => ['title', 'type'],
                'belongs_to' => ['user' => 'User', 'company' => 'Company', 'branch' => 'Branch'],
            ],
            'audit_logs' => [
                'table' => 'audit_logs', 'model' => 'AuditLog', 'route' => 'audit-logs',
                'permission_key' => 'audit_logs', 'label_key' => 'modules.audit_logs',
                'group' => 'system', 'icon' => 'bi-shield-check', 'soft_deletes' => false,
                'read_only' => true,
                'fields' => [
                    ['user_id', 'foreign', 'modules.users', ['model' => 'User', 'display' => 'name']],
                    ['company_id', 'foreign', 'common.company', ['model' => 'Company', 'display' => 'name']],
                    ['branch_id', 'foreign', 'common.branch', ['model' => 'Branch', 'display' => 'name']],
                    ['action', 'string', 'common.note'],
                    ['module', 'string', 'common.note'],
                    ['auditable_type', 'string', 'common.note'],
                    ['auditable_id', 'integer', 'common.note'],
                    ['old_values', 'json', 'common.note', ['read_only' => true]],
                    ['new_values', 'json', 'common.note', ['read_only' => true]],
                    ['ip_address', 'string', 'common.reference'],
                    ['user_agent', 'text', 'common.note', ['read_only' => true]],
                ],
                'searchable' => ['action', 'module'],
                'belongs_to' => ['user' => 'User', 'company' => 'Company', 'branch' => 'Branch'],
            ],
            'login_histories' => [
                'table' => 'login_histories', 'model' => 'LoginHistory', 'route' => 'login-histories',
                'permission_key' => 'login_histories', 'label_key' => 'modules.login_histories',
                'group' => 'system', 'icon' => 'bi-box-arrow-in-right', 'soft_deletes' => false,
                'read_only' => true,
                'fields' => [
                    ['user_id', 'foreign', 'modules.users', ['model' => 'User', 'display' => 'name']],
                    ['email_or_username', 'string', 'common.username'],
                    ['ip_address', 'string', 'common.reference'],
                    ['user_agent', 'text', 'common.note'],
                    ['status', 'enum', 'common.status', ['options' => ['success', 'failed']]],
                    ['failure_reason', 'string', 'common.note'],
                    ['logged_in_at', 'datetime', 'common.date'],
                ],
                'searchable' => ['email_or_username', 'ip_address'],
                'belongs_to' => ['user' => 'User'],
            ],
            'settings' => [
                'table' => 'settings', 'model' => 'Setting', 'route' => 'settings',
                'permission_key' => 'settings', 'label_key' => 'modules.settings',
                'group' => 'system', 'icon' => 'bi-gear', 'soft_deletes' => false,
                'fields' => [
                    ['company_id', 'foreign', 'common.company', ['model' => 'Company', 'display' => 'name']],
                    ['branch_id', 'foreign', 'common.branch', ['model' => 'Branch', 'display' => 'name']],
                    ['group', 'string', 'common.note', ['required' => true]],
                    ['key', 'string', 'common.code', ['required' => true]],
                    ['value', 'text', 'common.description'],
                    ['type', 'string', 'common.note', ['default' => 'text']],
                    ['is_public', 'bool', 'common.status', ['default' => false]],
                ],
                'searchable' => ['group', 'key'],
                'belongs_to' => ['company' => 'Company', 'branch' => 'Branch'],
            ],
            'code_sequences' => [
                'table' => 'code_sequences', 'model' => 'CodeSequence', 'route' => 'code-sequences',
                'permission_key' => 'code_sequences', 'label_key' => 'modules.code_sequences',
                'group' => 'system', 'icon' => 'bi-123', 'soft_deletes' => false,
                'fields' => [
                    ['company_id', 'foreign', 'common.company', ['model' => 'Company', 'display' => 'name']],
                    ['branch_id', 'foreign', 'common.branch', ['model' => 'Branch', 'display' => 'name']],
                    ['module', 'string', 'common.note', ['required' => true]],
                    ['prefix', 'string', 'common.code', ['required' => true]],
                    ['next_number', 'integer', 'common.amount', ['default' => 1]],
                    ['padding', 'integer', 'common.amount', ['default' => 6]],
                    ['format', 'string', 'common.note'],
                ],
                'searchable' => ['module', 'prefix'],
                'belongs_to' => ['company' => 'Company', 'branch' => 'Branch'],
            ],
        ];
    }

    /** All distinct permission keys (action suffixes are .view/.create/.edit/.delete) */
    public static function permissionList(): array
    {
        $perms = [];
        foreach (self::all() as $key => $cfg) {
            $p = $cfg['permission_key'];
            foreach (['view', 'create', 'edit', 'delete'] as $action) {
                $perms[] = [
                    'name' => "$p.$action",
                    'module' => $key,
                    'display_name' => ucfirst($action).' '.str_replace('_', ' ', $key),
                ];
            }
        }

        return $perms;
    }
}
